# Generated by Django 4.2.5 on 2023-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
